### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by zbeekman** [vmagnin/gtk-fortran#115]
Hi,

I'd like to create a mac OS [Homebrew](https://brew.sh) formula for this, but it looks like we probably need to resolve #56 first... or at least disable building shared libs on mac OS.

Also, I think parallel builds fail because you have multiple targets depending on the same Fortran sources that define modules. This is a weird CMake peculiarity, and can be avoided by creating an [object library](https://cmake.org/cmake/help/v3.1/command/add_library.html#object-libraries) first and then linking that into a static or dynamic library (or with executables etc.)

**Comment by vmagnin** [comment]
Hi @zbeekman 
concerning the parallel build issue, it is now fixed: see issue https://github.com/vmagnin/gtk-fortran/issues/79

**Comment by zbeekman** [comment]
@vmagnin are you going to mint a new release for this? Homebrew generally won't accept packages unless they're versioned. Once there's a new release (or tag, but an actual release is probably better) then I'll resurrect my Homebrew formula submission. Thanks!

**Comment by vmagnin** [comment]
> @vmagnin are you going to mint a new release for this? Homebrew generally won't accept packages unless they're versioned. Once there's a new release (or tag, but an actual release is probably better) then I'll resurrect my Homebrew formula submission. Thanks!

@zbeekman, yes I am planning a 19.04 release after the release of Ubuntu 19.04. Note that 19.04 refers to the Ubuntu version in which the gtk-fortran library (*-auto.f90) is generated, so our release could be in may or latter, depending on potential problems with latest GTK & GLib libraries and on the time available.

Yes I can do a real release, which will be archived by Zenodo. The PLplot problems are solved, the documentation has been entirely updated, many bugs/warnings have been solved and the current version has been tested under several Linux distributions, FreeBSD and MSYS2 / Windows.

Finally, it would be interesting if you can send me some comments on the commands needed to build gtk-fortran from source in macOS to put in the https://github.com/vmagnin/gtk-fortran/wiki page. I am not at all familiar with macOS. I know it's a Unix system but I do not know if there is some peculiarities concerning the use of CMake and make instructions...

**Comment by vmagnin** [comment]
@zbeekman 
gtk-fortran v19.04 has been released.

**Comment by zbeekman** [comment]
@vmagnin Been hacking around, but it seems #56 is still open and applicable to macOS: gfortran (8.3) is generating incorrect code from the apple linker's perspective: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59888

```
[ 84%] Linking Fortran shared library libgtk-3-fortran.dylib
cd /tmp/gtk-fortran-20190424-36870-ggjnvc/gtk-fortran-19.04.gtk3.24.8/build/src && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E cmake_link_script CMakeFiles/gtk-fortran_shared.dir/link.txt --verbose=1
/usr/local/bin/gfortran -pthread -O2 -fPIC -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 0.1.0 -current_version 0.1.0 -o libgtk-3-fortran.0.1.dylib -install_name @rpath/libgtk-3-fortran.0.1.dylib CMakeFiles/gtk-fortran_object.dir/atk-auto.f90.o CMakeFiles/gtk-fortran_object.dir/cairo-auto.f90.o CMakeFiles/gtk-fortran_object.dir/gdk-auto.f90.o CMakeFiles/gtk-fortran_object.dir/gdk-pixbuf-auto.f90.o CMakeFiles/gtk-fortran_object.dir/glib-auto.f90.o CMakeFiles/gtk-fortran_object.dir/gtk.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-container.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-button.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-entry.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-tree.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-menu.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-combobox.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-spin-slider.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-chooser.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-dialog.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-progress.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-accelerator.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-infobar.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-assistant.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-hl-misc.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-draw-hl.f90.o CMakeFiles/gtk-fortran_object.dir/gtk-sup.f90.o CMakeFiles/gtk-fortran_object.dir/gdk-pixbuf-hl.f90.o CMakeFiles/gtk-fortran_object.dir/pango-auto.f90.o CMakeFiles/gtk-fortran_object.dir/gdkevents-auto3.f90.o CMakeFiles/gtk-fortran_object.dir/unixonly-auto.f90.o  -L/usr/local/Cellar/plplot/5.14.0_1/lib -Wl,-rpath,/usr/local/Cellar/plplot/5.14.0_1/lib /usr/local/lib/libatk-1.0.dylib /usr/local/lib/libcairo.dylib /usr/local/lib/libgdk-3.0.dylib /usr/local/lib/libgdk_pixbuf-2.0.dylib /usr/local/lib/libglib-2.0.dylib /usr/local/lib/libgio-2.0.dylib /usr/local/lib/libgobject-2.0.dylib /usr/local/lib/libgtk-3.0.dylib /usr/local/lib/libpango-1.0.dylib
ld: illegal text-relocation to '_hl_gtk_listn_edit_cb' in CMakeFiles/gtk-fortran_object.dir/gtk-hl-tree.f90.o from 'lC72' in CMakeFiles/gtk-fortran_object.dir/gtk-hl-tree.f90.o for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libgtk-3-fortran.0.1.dylib] Error 1
make[1]: *** [src/CMakeFiles/gtk-fortran_shared.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by vmagnin** [comment]
@zbeekman 
OK. I don't know how it is with macOS, but in the latest Ubuntu 19.04 there is an experimental package with gfortran 9.0.1, which is building gtk-fortran without problem in Ubuntu, as gfortran 8.3.0.
Perhaps gfortran 9 will improve things in macOS, or perhaps not... Some bugs have a long life...

**Comment by zbeekman** [comment]
Maybe you could ping the GCC/GFortran mailing list/devs about this: It seems to happen with ISO_C_Binding a fair amount on macOS. Maybe @jerryd has thoughts.

**Comment by vmagnin** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59888

**Comment by han190** [comment]
It would be really nice if gtk-fortran could be wrapped into Homebrew. Yet the issue mentioned above still exists on macOS(Mojave)
```
[ 23%] Built target gtk-fortran_object
Scanning dependencies of target gtk-fortran_shared
[ 23%] Linking Fortran shared library libgtk-3-fortran.dylib
ld: illegal text-relocation to '_hl_gtk_listn_edit_cb' in CMakeFiles/gtk-fortran_object.dir/gtk-hl-tree.f90.o from 'lC72' in CMakeFiles/gtk-fortran_object.dir/gtk-hl-tree.f90.o for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libgtk-3-fortran.0.1.dylib] Error 1
make[1]: *** [src/CMakeFiles/gtk-fortran_shared.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by zbeekman** [comment]
The GFortran bug is a blocker. I don't know that I've tried with 9 yet, but the bug is still open which doesn't give me much confidence. If you go make some noise on the GFortran bug report that could help.

**Comment by han190** [comment]
Hi, a little update. I tried to compile gtk-fortran through intel fortran and it works well (I disabled plplot).

```
MacBook-Pro:build$ cmake -D EXCLUDE_PLPLOT=disable ..
-- Compiler: Intel 19.0.5.20190816 /usr/local/bin/ifort
-- Build type is: release
-- Compilation flags: -O3 -mtune=native -march=native
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- PLPLOT Excluded as command option
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/han/Documents/gtk-fortran/build
```
![image](https://user-images.githubusercontent.com/13799118/66375315-93a5f980-e959-11e9-99fc-0fed63345860.png)

**Comment by vmagnin** [comment]
Hi @han190 
thank you for that information. I have Intel Fortran 15 and it fails to build gtk-fortran under Linux (https://github.com/vmagnin/gtk-fortran/issues/97). I am happy to see it's OK with Intel Fortran 19, under Mac. 

Of course, it would be better for Mac users if the free gfortran can do the same. But some bugs have a long life, sometimes several years...

**Comment by zbeekman** [comment]
It looks like this GFortran bug is finally getting some attention. I'm hopeful fixes will be in the next GFortran release.

**Comment by vmagnin** [comment]
Hi @zbeekman  and @han190 ,
it seems the bug is now fixed, at least in gfortran 7.5: see this comment https://github.com/vmagnin/gtk-fortran/issues/154#issuecomment-559383016

**Comment by han190** [comment]
@vmagnin Thanks. I just tried it and it works. But there is a typo in your wiki page. It should be `mkdir` instead of `make`
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
mkdir build && cd build
```

**Comment by vmagnin** [comment]
> @vmagnin Thanks. I just tried it and it works. But there is a typo in your wiki page. It should be `mkdir` instead of `make`

@han190 , thank you for your vigilance, it is corrected.
Which gfortran version have you tested ? 7.5 or a more recent one ? (I do no know if the fix has been propagated in all versions)

**Comment by han190** [comment]
Hi, I only tested 7.5 yesterday. I just tested 9.2.0 and it is still not fixed.

**Comment by nano8ot** [comment]
hi

the fortran compilers are as follows:

$ gfortran --version
GNU Fortran (Homebrew GCC 9.3.0) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

when i compile with gfortran
gfortran gtkhello.f90 $(pkg-config --cflags --libs gtk-3-fortran)

the error i receive is:
f951: Fatal Error: Reading module 'gtk' at line 1 column 2: Unexpected EOF
compilation terminated.

$ ifort --version
ifort (IFORT) 19.1.0.166 20191121
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.

when i compile with ifort, i get following error:
ld: unknown option: -R/usr/local/lib

gtk-3-fortran lib was compiled with ifort.

pkg-config --cflags --libs gtk-3-fortran output is:
-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/include/gtk-3-fortran -I/usr/local/Cellar/gtk+3/3.24.14/include/gtk-3.0 -I/usr/local/Cellar/glib/2.64.1/include/gio-unix-2.0 -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/libepoxy/1.5.4/include -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.9/include/fribidi -I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.13/include -I/usr/local/Cellar/atk/2.34.1/include/atk-1.0 -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/glib/2.64.1/include -I/usr/local/Cellar/glib/2.64.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.64.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.44/include -L/usr/local/Cellar/gtk+3/3.24.14/lib -L/usr/local/Cellar/pango/1.44.7/lib -L/usr/local/Cellar/harfbuzz/2.6.4/lib -L/usr/local/Cellar/atk/2.34.1/lib -L/usr/local/Cellar/cairo/1.16.0_2/lib -L/usr/local/Cellar/gdk-pixbuf/2.40.0/lib -L/usr/local/Cellar/glib/2.64.1/lib -L/usr/local/opt/gettext/lib -Xlinker -R/usr/local/lib -lgtk-3-fortran -lgtk-3 -lgdk-3 -framework Cocoa -framework Carbon -framework CoreGraphics -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl

thanks i advance for help to resolve this problem.
with kind regards
jk

**Comment by vmagnin** [comment]
Hi @nano8ot 
I have no macOS machine, so I do not know if I can help you.

Have you followed the instructions given here for macOS ?
https://github.com/vmagnin/gtk-fortran/wiki#macos

Concerning the first error, _"f951: Fatal Error: Reading module 'gtk' at line 1 column 2: Unexpected EOF",_ I have found:
https://stackoverflow.com/questions/54824530/msys2-f951-exe-fatal-error-reading-module-at-line-2-column-1-unexpec
It seems to be a gcc bug. Have you tested with gfortran 7.5 ? (see @han190 message)

gfortran 7.5 is the more debugged version amidst the versions still maintained:
https://gcc.gnu.org/gcc-7/
Older is sometimes better.

**Comment by nano8ot** [comment]
hi @vmagnin 

thanks for the answer. i took my chances with gfortran 9.3.
i followed all the instructions.

strangely, all examples compiles with cmake, make, with no errors.
thanks for the links. i look into them.

have a nice day

**Comment by vmagnin** [comment]
@nano8ot 
Fine !
I think the bug has not yet been integrated in more recent versions of gfortran. But you can try gfortran 8... Perhaps it was corrected in GCC 8.4 (Mar 4, 2020): https://gcc.gnu.org/gcc-8/
